version: '3'
services:
  mongo:
    image: mongo
    container_name: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  backend:
    build: ./backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
    env_file:
      - ./backend/.env
    depends_on:
      - mongo

  frontend:
    build:
      context: ./frontend
      args:
        - REACT_APP_BACKEND_URL=https://bitetrack-production-052d.up.railway.app
    ports:
      - "8000:80"
    depends_on:
      - backend

volumes:
  mongo-data:
